---
title: "PPC Analysis"
author: "Jens Laufer"
date: "6 12 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

```{r}
library(tidyverse)
library(ppctools)
library(scales)
library(ggthemes)
```




```{r}
getTrafficForProfitData <- function(profit) {
  expand_grid(
    product_cost = seq(10, 150, 10),
    cpc = seq(0.1, 1, 0.1),
    cr = seq(0.01, 0.05, 0.01),
    ctr = seq(0.01, 0.05, 0.01)
  ) %>%
    mutate(ocr = cr * ctr) %>%
    mutate(profit = profit) %>%
    mutate(traffic_for_profit = traffic_for_profit(profit, product_cost, cpc, cr, ctr)) %>%
    filter(is.finite(traffic_for_profit))
}
```




```{r fig.height=10, fig.width=20}

getTrafficForProfitData(3000) %>% filter(traffic_for_profit>0) %>% 
  arrange(traffic_for_profit) %>%
  mutate(isTrafficRealistic=(traffic_for_profit<50000)) %>% 
  ggplot(aes(x = product_cost, y = traffic_for_profit, color=isTrafficRealistic, size=cpc), alpha=.3) +
  scale_y_continuous(trans = "log10", labels=comma)+
  scale_color_tableau() +
  geom_point()
```

```{r}
getProfitData <- function() {
  expand_grid(
    traffic = seq(1000, 100000, 1000),
    product_cost = seq(10, 120, 10),
    cpc = seq(0.1, 1.2, 0.1),
    cr = seq(0.01, 0.05, 0.01),
    ctr = seq(0.01, 0.05, 0.01)
  ) %>%
    mutate(ocr = cr * ctr) %>%
    mutate(profit = profit_for_specified_traffic(
      traffic = traffic,
      cpc = cpc,
      product_cost = product_cost,
      cr = cr,
      ctr = ctr
    ))
}
```

```{r}
.05^2 * 1000
```


```{r}
data <- getProfitData()
```


```{r fig.height=10, fig.width=20}
data %>%
  filter(profit > 0) %>% 
  mutate(loss = profit < 0) %>%
  mutate(product_cost_bin = cut(product_cost, include.lowest = T, breaks = c(0,20,40,60,80,100,130)),
         ocr_cut = cut(ocr * 1000, breaks=c(0,0.5,1.0,1.5,2,2.55), include.lowest = T),
         cpc_cut = cut(cpc, breaks=c(0,.2,.4,.6,.8,1,1.26), include.lowest = T)) %>%
  ggplot(aes(x = traffic, y = profit, color = ocr_cut)) +
  geom_point() +
  annotate("rect", xmin=5000, xmax=40000, ymin=2000, ymax=Inf, color="grey", alpha=.4) +
  scale_color_tableau() +
  scale_y_continuous(trans = "identity", labels = comma) +
  scale_x_continuous(trans = "identity", labels = comma) +
  facet_grid( ~ product_cost_bin ~ cpc_cut, scales = "free")
```




